name: Validate Kubernetes Manifests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  validate:
    name: Kubernetes Manifest Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Kustomize
        run: |
          curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
          sudo mv kustomize /usr/local/bin/

      - name: Kustomize Build
        run: |
          mkdir -p manifests
          kustomize build k8s/ > manifests/combined.yaml

      - name: Install kubeconform
        run: |
          curl -L https://github.com/yannh/kubeconform/releases/latest/download/kubeconform-linux-amd64.tar.gz | tar xz
          sudo mv kubeconform /usr/local/bin/
          

      - name: Validate manifests with kubeconform
        run: |
          kubeconform -strict -verbose -summary manifests/combined.yaml

      - name: Dry-run kubectl apply (validation only)
        run: |
          kubectl apply -f manifests/combined.yaml --dry-run=client --validate=false
